require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['**/*test*.rb']
  t.verbose = false
end

desc 'convert all budgetary pdf to html'
task :pdf2html do
  puts 'Not implemented'
end

namespace "pdf2html" do
  desc 'covert only cover pages from budgetary pdf to html'
  task :only_cover do
    system 'TEST=pdf_converter_test.rb TESTOPTS="--name=test_extract_only_cover" rake test'
  end
end

desc 'parse budgetary html to csv'
task :parse do
end