require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['**/*test*.rb']
  t.verbose = false
end

desc 'convert all budgetary pdf to html'
task :pdf2html do
  system 'TEST=pdf_converter_test.rb TESTOPTS="--name=test_extract_all" rake test'
end

namespace 'pdf2html' do
  desc 'covert only cover pages from budgetary pdf to html'
  task :only_cover do
    system 'TEST=pdf_converter_test.rb TESTOPTS="--name=test_extract_only_cover" rake test'
  end
end

desc 'parse budgetary html to csv'
task :parse do
  system 'TEST=parser_test.rb TESTOPTS="--name=test_parse_returns_correct_csv" rake test'
end

namespace 'test' do
  desc 'run only parser tests'
  task :parser do
    system 'TEST=parser_test.rb rake test'
  end
end